version: '3.7'

services:

    client:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - "3000:3000"
        volumes: 
            - ./frontend:/app
            - /app/node_modules
        networks:
            - app-tier

    mongodb:
        image: mongo
        container_name: mongo
        ports:
            - "27017:27017"
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "password"
            MONGO_INITDB_DATABASE: webapp
            MONGODB_DATA_DIR: /data/db
        volumes:
            - mongodbdata:/data/db
        networks:
            - app-tier

    api:
        build: 
            context: ./backend
            dockerfile: Dockerfile
        command: gunicorn -w 1 -b 0.0.0.0:5000 server:app --reload
        ports:
            - "5000:5000"
        volumes:
            - appdata:/var/www/
        links:
            - mongodb:mongodb   
        depends_on: 
            - mongodb
        networks:
            - app-tier
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "8000:8000"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - client
            - api
        networks:
            - app-tier
        restart: "on-failure"
        
    redis:
        image: redis:latest
        container_name: redis
        hostname: redis_dev
        networks:
            - app-tier
        
networks:
    app-tier:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
    appdata:
        driver: local